version: '3.4'

services:
  database:
    container_name: postgresdb
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#     SQL to create tables in db
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#      load starter data
      - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
              POSTGRES_USER: ${POSTGRES_USER:-postgres}
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
              POSTGRES_DB: SkillPlant
              PGDATA: /data/postgres

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
#      PGADMIN_LISTEN_PORT = 80

    ports:
      - "5050:80"



volumes:
  pgdata:



#    postgres:
#        container_name: postgres_container
#        image: postgres:10.5
#        restart: always
#        environment:
#          POSTGRES_USER: ${POSTGRES_USER:-postgres}
#          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#          PGDATA: /data/postgres
#        logging:
#          options:
#            max-size: 10m
#            max-file: "3"
#        ports:
#          - '5438:5432'
#        volumes:
#          - ./postgres-data:/var/lib/postgresql/data
#          # copy the sql script to create tables
#          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#          # copy the sql script to fill tables
#          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql